"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { cn } from "@/lib/utils";

/**
 * Smart Summary Card Component
 * 
 * Displays an AI-generated summary of a call in a card with a light
 * yellow/gray background. Content is displayed as an unordered list
 * of bullet points.
 * 
 * @example
 * ```tsx
 * <SmartSummary
 *   summary={[
 *     "Client inquired about estate planning services",
 *     "Discussed will preparation and trust setup",
 *     "Scheduled follow-up consultation for next week",
 *   ]}
 * />
 * ```
 */

export interface SmartSummaryProps {
  /**
   * Array of bullet points (summary items)
   */
  summary: string[];
  /**
   * Optional title for the summary card
   * @default "Summary"
   */
  title?: string;
  /**
   * Additional CSS classes
   */
  className?: string;
}

/**
 * Smart Summary Card Component
 * 
 * Features:
 * - Card with light yellow/gray background (bg-yellow-50/50 or bg-zinc-50)
 * - Unordered list of bullet points
 * - Generated by LLM (from API)
 */
export const SmartSummary = React.memo(function SmartSummary({
  summary,
  title = "Summary",
  className,
}: SmartSummaryProps) {
  if (summary.length === 0) {
    return (
      <Card
        className={cn(
          "bg-yellow-50/50 dark:bg-zinc-50/10",
          className
        )}
      >
        <CardContent className="pt-6">
          <p className="text-sm text-muted-foreground">
            No summary available
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card
      className={cn(
        // Light yellow/gray background as per design spec
        "bg-yellow-50/50 dark:bg-zinc-50/10",
        className
      )}
    >
      <CardHeader className="pb-3">
        <CardTitle className="text-base font-semibold">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <ul className="space-y-2">
          {summary.map((item, index) => (
            <li
              key={index}
              className="text-sm text-foreground flex items-start gap-2"
            >
              {/* Bullet point */}
              <span className="text-muted-foreground mt-1.5 flex-shrink-0">
                •
              </span>
              {/* Summary text */}
              <span className="flex-1">{item}</span>
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  );
});

