// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: cognitive_orch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CognitiveOrchestrator_ProcessText_FullMethodName          = "/cognitive_orch.CognitiveOrchestrator/ProcessText"
	CognitiveOrchestrator_GetConversationState_FullMethodName = "/cognitive_orch.CognitiveOrchestrator/GetConversationState"
	CognitiveOrchestrator_ClearConversation_FullMethodName    = "/cognitive_orch.CognitiveOrchestrator/ClearConversation"
	CognitiveOrchestrator_HealthCheck_FullMethodName          = "/cognitive_orch.CognitiveOrchestrator/HealthCheck"
)

// CognitiveOrchestratorClient is the client API for CognitiveOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Cognitive Orchestrator gRPC Service
type CognitiveOrchestratorClient interface {
	// Process text input and stream response (primary method for voice conversations)
	ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextResponse], error)
	// Get current conversation state
	GetConversationState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	// Clear conversation state
	ClearConversation(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cognitiveOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewCognitiveOrchestratorClient(cc grpc.ClientConnInterface) CognitiveOrchestratorClient {
	return &cognitiveOrchestratorClient{cc}
}

func (c *cognitiveOrchestratorClient) ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveOrchestrator_ServiceDesc.Streams[0], CognitiveOrchestrator_ProcessText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TextRequest, TextResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveOrchestrator_ProcessTextClient = grpc.ServerStreamingClient[TextResponse]

func (c *cognitiveOrchestratorClient) GetConversationState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, CognitiveOrchestrator_GetConversationState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveOrchestratorClient) ClearConversation(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, CognitiveOrchestrator_ClearConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveOrchestratorClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CognitiveOrchestrator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognitiveOrchestratorServer is the server API for CognitiveOrchestrator service.
// All implementations must embed UnimplementedCognitiveOrchestratorServer
// for forward compatibility.
//
// Cognitive Orchestrator gRPC Service
type CognitiveOrchestratorServer interface {
	// Process text input and stream response (primary method for voice conversations)
	ProcessText(*TextRequest, grpc.ServerStreamingServer[TextResponse]) error
	// Get current conversation state
	GetConversationState(context.Context, *StateRequest) (*StateResponse, error)
	// Clear conversation state
	ClearConversation(context.Context, *ClearRequest) (*ClearResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCognitiveOrchestratorServer()
}

// UnimplementedCognitiveOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognitiveOrchestratorServer struct{}

func (UnimplementedCognitiveOrchestratorServer) ProcessText(*TextRequest, grpc.ServerStreamingServer[TextResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessText not implemented")
}
func (UnimplementedCognitiveOrchestratorServer) GetConversationState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationState not implemented")
}
func (UnimplementedCognitiveOrchestratorServer) ClearConversation(context.Context, *ClearRequest) (*ClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearConversation not implemented")
}
func (UnimplementedCognitiveOrchestratorServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCognitiveOrchestratorServer) mustEmbedUnimplementedCognitiveOrchestratorServer() {}
func (UnimplementedCognitiveOrchestratorServer) testEmbeddedByValue()                               {}

// UnsafeCognitiveOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognitiveOrchestratorServer will
// result in compilation errors.
type UnsafeCognitiveOrchestratorServer interface {
	mustEmbedUnimplementedCognitiveOrchestratorServer()
}

func RegisterCognitiveOrchestratorServer(s grpc.ServiceRegistrar, srv CognitiveOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedCognitiveOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognitiveOrchestrator_ServiceDesc, srv)
}

func _CognitiveOrchestrator_ProcessText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveOrchestratorServer).ProcessText(m, &grpc.GenericServerStream[TextRequest, TextResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveOrchestrator_ProcessTextServer = grpc.ServerStreamingServer[TextResponse]

func _CognitiveOrchestrator_GetConversationState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveOrchestratorServer).GetConversationState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveOrchestrator_GetConversationState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveOrchestratorServer).GetConversationState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveOrchestrator_ClearConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveOrchestratorServer).ClearConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveOrchestrator_ClearConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveOrchestratorServer).ClearConversation(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveOrchestrator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveOrchestratorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveOrchestrator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveOrchestratorServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CognitiveOrchestrator_ServiceDesc is the grpc.ServiceDesc for CognitiveOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognitiveOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cognitive_orch.CognitiveOrchestrator",
	HandlerType: (*CognitiveOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversationState",
			Handler:    _CognitiveOrchestrator_GetConversationState_Handler,
		},
		{
			MethodName: "ClearConversation",
			Handler:    _CognitiveOrchestrator_ClearConversation_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CognitiveOrchestrator_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessText",
			Handler:       _CognitiveOrchestrator_ProcessText_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cognitive_orch.proto",
}
