// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cognitive_orch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to process text input
type TextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Optional: existing conversation ID
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                           // User's transcribed text
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // User identifier
	FirmId         string                 `protobuf:"bytes,4,opt,name=firm_id,json=firmId,proto3" json:"firm_id,omitempty"`                         // Firm/tenant identifier
	IncludeRag     bool                   `protobuf:"varint,5,opt,name=include_rag,json=includeRag,proto3" json:"include_rag,omitempty"`            // Enable RAG context retrieval
	ToolsEnabled   bool                   `protobuf:"varint,6,opt,name=tools_enabled,json=toolsEnabled,proto3" json:"tools_enabled,omitempty"`      // Enable tool/function calling
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`                                         // Optional: model override (e.g., "azure/gpt-4o")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_cognitive_orch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TextRequest) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *TextRequest) GetIncludeRag() bool {
	if x != nil {
		return x.IncludeRag
	}
	return false
}

func (x *TextRequest) GetToolsEnabled() bool {
	if x != nil {
		return x.ToolsEnabled
	}
	return false
}

func (x *TextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// Streaming response chunks
type TextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*TextResponse_TextChunk
	//	*TextResponse_ToolCall
	//	*TextResponse_ToolResult
	//	*TextResponse_Error
	Content        isTextResponse_Content `protobuf_oneof:"content"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Conversation ID (for correlation)
	IsDone         bool                   `protobuf:"varint,6,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`                        // True when stream is complete
	TotalTokens    int32                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`         // Optional: token count (if available)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_cognitive_orch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetContent() isTextResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TextResponse) GetTextChunk() string {
	if x != nil {
		if x, ok := x.Content.(*TextResponse_TextChunk); ok {
			return x.TextChunk
		}
	}
	return ""
}

func (x *TextResponse) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Content.(*TextResponse_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *TextResponse) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Content.(*TextResponse_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *TextResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Content.(*TextResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *TextResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TextResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *TextResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type isTextResponse_Content interface {
	isTextResponse_Content()
}

type TextResponse_TextChunk struct {
	TextChunk string `protobuf:"bytes,1,opt,name=text_chunk,json=textChunk,proto3,oneof"` // Text content chunk
}

type TextResponse_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"` // Tool call request (for logging/debugging)
}

type TextResponse_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"` // Tool execution result (for logging/debugging)
}

type TextResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"` // Error occurred
}

func (*TextResponse_TextChunk) isTextResponse_Content() {}

func (*TextResponse_ToolCall) isTextResponse_Content() {}

func (*TextResponse_ToolResult) isTextResponse_Content() {}

func (*TextResponse_Error) isTextResponse_Content() {}

// Tool call information (for observability)
type ToolCall struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolName       string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ParametersJson string                 `protobuf:"bytes,2,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON string of tool parameters
	CallId         string                 `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_cognitive_orch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *ToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// Tool execution result (for observability)
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON string of tool result
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // If success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_cognitive_orch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Error information
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                  // Error code (e.g., "TOOL_EXECUTION_FAILED")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                            // Human-readable error message
	DetailsJson   string                 `protobuf:"bytes,3,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"` // Optional: additional error details (JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_cognitive_orch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

// Request conversation state
type StateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_cognitive_orch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{5}
}

func (x *StateRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Conversation state response
type StateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                           // Conversation history
	TotalTokens    int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"` // Total tokens used
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirmId         string                 `protobuf:"bytes,5,opt,name=firm_id,json=firmId,proto3" json:"firm_id,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt      int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_cognitive_orch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{6}
}

func (x *StateResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StateResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *StateResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *StateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StateResponse) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *StateResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StateResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Individual message in conversation
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user", "assistant", "system", "tool"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // Unix timestamp
	ToolCallId    string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // Optional: if role="tool"
	ToolName      string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`         // Optional: if role="tool"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cognitive_orch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

// Clear conversation request
type ClearRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_cognitive_orch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{8}
}

func (x *ClearRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Clear conversation response
type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_cognitive_orch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{9}
}

func (x *ClearResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cognitive_orch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{10}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // "healthy", "degraded", "unhealthy"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Service version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cognitive_orch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognitive_orch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cognitive_orch_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_cognitive_orch_proto protoreflect.FileDescriptor

const file_cognitive_orch_proto_rawDesc = "" +
	"\n" +
	"\x14cognitive_orch.proto\x12\x0ecognitive_orch\"\xd8\x01\n" +
	"\vTextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\afirm_id\x18\x04 \x01(\tR\x06firmId\x12\x1f\n" +
	"\vinclude_rag\x18\x05 \x01(\bR\n" +
	"includeRag\x12#\n" +
	"\rtools_enabled\x18\x06 \x01(\bR\ftoolsEnabled\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\"\xc6\x02\n" +
	"\fTextResponse\x12\x1f\n" +
	"\n" +
	"text_chunk\x18\x01 \x01(\tH\x00R\ttextChunk\x127\n" +
	"\ttool_call\x18\x02 \x01(\v2\x18.cognitive_orch.ToolCallH\x00R\btoolCall\x12=\n" +
	"\vtool_result\x18\x03 \x01(\v2\x1a.cognitive_orch.ToolResultH\x00R\n" +
	"toolResult\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.cognitive_orch.ErrorH\x00R\x05error\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12\x17\n" +
	"\ais_done\x18\x06 \x01(\bR\x06isDone\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x05R\vtotalTokensB\t\n" +
	"\acontent\"i\n" +
	"\bToolCall\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12'\n" +
	"\x0fparameters_json\x18\x02 \x01(\tR\x0eparametersJson\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"\x85\x01\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"X\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fdetails_json\x18\x03 \x01(\tR\vdetailsJson\"7\n" +
	"\fStateRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x80\x02\n" +
	"\rStateResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.cognitive_orch.MessageR\bmessages\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x17\n" +
	"\afirm_id\x18\x05 \x01(\tR\x06firmId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x94\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\"7\n" +
	"\fClearRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"C\n" +
	"\rClearResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xd8\x02\n" +
	"\x15CognitiveOrchestrator\x12J\n" +
	"\vProcessText\x12\x1b.cognitive_orch.TextRequest\x1a\x1c.cognitive_orch.TextResponse0\x01\x12S\n" +
	"\x14GetConversationState\x12\x1c.cognitive_orch.StateRequest\x1a\x1d.cognitive_orch.StateResponse\x12P\n" +
	"\x11ClearConversation\x12\x1c.cognitive_orch.ClearRequest\x1a\x1d.cognitive_orch.ClearResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.cognitive_orch.HealthRequest\x1a\x1e.cognitive_orch.HealthResponseB>Z<github.com/lexiqai/voice-gateway/internal/orchestrator/protob\x06proto3"

var (
	file_cognitive_orch_proto_rawDescOnce sync.Once
	file_cognitive_orch_proto_rawDescData []byte
)

func file_cognitive_orch_proto_rawDescGZIP() []byte {
	file_cognitive_orch_proto_rawDescOnce.Do(func() {
		file_cognitive_orch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognitive_orch_proto_rawDesc), len(file_cognitive_orch_proto_rawDesc)))
	})
	return file_cognitive_orch_proto_rawDescData
}

var file_cognitive_orch_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cognitive_orch_proto_goTypes = []any{
	(*TextRequest)(nil),    // 0: cognitive_orch.TextRequest
	(*TextResponse)(nil),   // 1: cognitive_orch.TextResponse
	(*ToolCall)(nil),       // 2: cognitive_orch.ToolCall
	(*ToolResult)(nil),     // 3: cognitive_orch.ToolResult
	(*Error)(nil),          // 4: cognitive_orch.Error
	(*StateRequest)(nil),   // 5: cognitive_orch.StateRequest
	(*StateResponse)(nil),  // 6: cognitive_orch.StateResponse
	(*Message)(nil),        // 7: cognitive_orch.Message
	(*ClearRequest)(nil),   // 8: cognitive_orch.ClearRequest
	(*ClearResponse)(nil),  // 9: cognitive_orch.ClearResponse
	(*HealthRequest)(nil),  // 10: cognitive_orch.HealthRequest
	(*HealthResponse)(nil), // 11: cognitive_orch.HealthResponse
}
var file_cognitive_orch_proto_depIdxs = []int32{
	2,  // 0: cognitive_orch.TextResponse.tool_call:type_name -> cognitive_orch.ToolCall
	3,  // 1: cognitive_orch.TextResponse.tool_result:type_name -> cognitive_orch.ToolResult
	4,  // 2: cognitive_orch.TextResponse.error:type_name -> cognitive_orch.Error
	7,  // 3: cognitive_orch.StateResponse.messages:type_name -> cognitive_orch.Message
	0,  // 4: cognitive_orch.CognitiveOrchestrator.ProcessText:input_type -> cognitive_orch.TextRequest
	5,  // 5: cognitive_orch.CognitiveOrchestrator.GetConversationState:input_type -> cognitive_orch.StateRequest
	8,  // 6: cognitive_orch.CognitiveOrchestrator.ClearConversation:input_type -> cognitive_orch.ClearRequest
	10, // 7: cognitive_orch.CognitiveOrchestrator.HealthCheck:input_type -> cognitive_orch.HealthRequest
	1,  // 8: cognitive_orch.CognitiveOrchestrator.ProcessText:output_type -> cognitive_orch.TextResponse
	6,  // 9: cognitive_orch.CognitiveOrchestrator.GetConversationState:output_type -> cognitive_orch.StateResponse
	9,  // 10: cognitive_orch.CognitiveOrchestrator.ClearConversation:output_type -> cognitive_orch.ClearResponse
	11, // 11: cognitive_orch.CognitiveOrchestrator.HealthCheck:output_type -> cognitive_orch.HealthResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cognitive_orch_proto_init() }
func file_cognitive_orch_proto_init() {
	if File_cognitive_orch_proto != nil {
		return
	}
	file_cognitive_orch_proto_msgTypes[1].OneofWrappers = []any{
		(*TextResponse_TextChunk)(nil),
		(*TextResponse_ToolCall)(nil),
		(*TextResponse_ToolResult)(nil),
		(*TextResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognitive_orch_proto_rawDesc), len(file_cognitive_orch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cognitive_orch_proto_goTypes,
		DependencyIndexes: file_cognitive_orch_proto_depIdxs,
		MessageInfos:      file_cognitive_orch_proto_msgTypes,
	}.Build()
	File_cognitive_orch_proto = out.File
	file_cognitive_orch_proto_goTypes = nil
	file_cognitive_orch_proto_depIdxs = nil
}
