"""Generated Protocol Buffer files for Cognitive Orchestrator gRPC service.

This directory contains auto-generated Python code from cognitive_orch.proto.
Do not edit these files manually - they are generated by the proto compilation script.
"""

# Import generated proto modules to make them available via this package
try:
    from cognitive_orch.grpc.proto import cognitive_orch_pb2
    from cognitive_orch.grpc.proto import cognitive_orch_pb2_grpc

    __all__ = ["cognitive_orch_pb2", "cognitive_orch_pb2_grpc"]
except ImportError as e:
    # If proto files haven't been generated yet, this will fail
    # This is expected during initial setup
    import warnings
    warnings.warn(
        f"Could not import generated proto files: {e}. "
        "Run 'make proto-compile' to generate them.",
        ImportWarning
    )
    __all__ = []

