"use client";

import { useState, useMemo, useCallback } from "react";
import { UploadZone } from "@/components/knowledge/UploadZone";
import { FileDataTable, type FileMetadata } from "@/components/knowledge/FileDataTable";
import { FileTableSkeleton } from "@/components/knowledge/FileTableSkeleton";
import { VerificationChat, type ChatMessage } from "@/components/knowledge/VerificationChat";
import { ErrorState } from "@/components/ui/ErrorState";
import { EmptyState } from "@/components/ui/EmptyState";
import { FileText } from "lucide-react";
import { cn } from "@/lib/utils";

// Force dynamic rendering because layout uses client components
export const dynamic = "force-dynamic";

/**
 * Knowledge Base Page
 * 
 * RAG Manager for uploading, managing, and testing knowledge base documents.
 * 
 * Layout:
 * - Single Column, Max-Width: Centered layout (like document editor)
 * - Sections (Top to Bottom):
 *   - Upload Zone
 *   - File Data Table
 *   - Verification Chat
 */
export default function KnowledgeBasePage() {
  // File management state
  const [files, setFiles] = useState<FileMetadata[]>([]);
  const [highlightedFileId, setHighlightedFileId] = useState<string | null>(null);
  // Loading state - will be replaced with actual hook loading states
  const [isLoadingFiles, setIsLoadingFiles] = useState(false);
  // Error state - will be replaced with actual hook error states
  const [filesError, setFilesError] = useState<Error | null>(null);

  // Chat state
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  // Mock initial files for demonstration
  const mockFiles: FileMetadata[] = useMemo(
    () => [
      {
        id: "file-1",
        name: "fee-schedule.pdf",
        date: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
        size: 1024 * 512, // 512 KB
        status: "ready",
      },
      {
        id: "file-2",
        name: "terms-of-service.pdf",
        date: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
        size: 1024 * 1024 * 2, // 2 MB
        status: "ready",
      },
      {
        id: "file-3",
        name: "client-handbook.pdf",
        date: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
        size: 1024 * 1024 * 5, // 5 MB
        status: "processing",
      },
    ],
    []
  );

  // Initialize with mock files if empty
  useMemo(() => {
    if (files.length === 0) {
      setFiles(mockFiles);
    }
  }, [files.length, mockFiles]);

  /**
   * Handle file upload
   */
  const handleFileSelect = useCallback((selectedFiles: File[]) => {
    const newFiles: FileMetadata[] = selectedFiles.map((file, index) => ({
      id: `file-${Date.now()}-${index}`,
      name: file.name,
      date: new Date(),
      size: file.size,
      status: "processing" as const,
    }));

    setFiles((prev) => [...newFiles, ...prev]);

    // Simulate processing completion after 3 seconds
    setTimeout(() => {
      setFiles((prev) =>
        prev.map((f) =>
          newFiles.some((nf) => nf.id === f.id)
            ? { ...f, status: "ready" as const }
            : f
        )
      );
    }, 3000);
  }, []);

  /**
   * Handle file deletion
   */
  const handleDelete = useCallback((fileId: string) => {
    setFiles((prev) => prev.filter((f) => f.id !== fileId));
  }, []);

  /**
   * Handle file re-indexing
   */
  const handleReindex = useCallback((fileId: string) => {
    setFiles((prev) =>
      prev.map((f) =>
        f.id === fileId ? { ...f, status: "processing" as const } : f
      )
    );

    // Simulate re-indexing completion after 2 seconds
    setTimeout(() => {
      setFiles((prev) =>
        prev.map((f) =>
          f.id === fileId ? { ...f, status: "ready" as const } : f
        )
      );
    }, 2000);
  }, []);

  /**
   * Handle sending a chat message
   */
  const handleSendMessage = useCallback(
    async (message: string) => {
      // Add user message
      const userMessage: ChatMessage = {
        role: "user",
        content: message,
      };
      setMessages((prev) => [...prev, userMessage]);
      setIsLoading(true);

      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 1500));

      // Mock response based on message content
      const assistantMessage: ChatMessage = {
        role: "assistant",
        content: `Based on the uploaded documents, I can help you with that. Here's what I found regarding "${message}":\n\n[This is a mock response. In production, this would be generated by the RAG system using the indexed knowledge base.]`,
        sources: files
          .filter((f) => f.status === "ready")
          .slice(0, 2)
          .map((f) => f.id),
      };

      setMessages((prev) => [...prev, assistantMessage]);
      setIsLoading(false);
    },
    [files]
  );

  /**
   * Handle source hover (highlight file in table)
   */
  const handleSourceHover = useCallback((sourceId: string) => {
    setHighlightedFileId(sourceId);
  }, []);

  /**
   * Handle source leave (clear highlight)
   */
  const handleSourceLeave = useCallback(() => {
    setHighlightedFileId(null);
  }, []);

  return (
    <div className="mx-auto w-full max-w-4xl space-y-6 px-4 py-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-zinc-900 dark:text-zinc-100">
          Knowledge Base
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Upload and manage documents for your AI agent's knowledge base
        </p>
      </div>

      {/* Upload Zone */}
      <UploadZone
        onFileSelect={handleFileSelect}
        accept=".pdf"
        maxSize={10 * 1024 * 1024} // 10MB
      />

      {/* File Data Table */}
      {filesError ? (
        <ErrorState
          error={filesError}
          onRetry={() => {
            setFilesError(null);
            // In real implementation, this would call refetch()
          }}
          title="Failed to load files"
          inline
        />
      ) : isLoadingFiles ? (
        <FileTableSkeleton count={5} />
      ) : files.length === 0 ? (
        <EmptyState
          icon={<FileText className="h-12 w-12" />}
          title="No files uploaded"
          description="Upload PDF documents to build your knowledge base. Drag and drop files above or click to browse."
          size="default"
        />
      ) : (
        <FileDataTable
          files={files}
          onDelete={handleDelete}
          onReindex={handleReindex}
          highlightedFileId={highlightedFileId}
        />
      )}

      {/* Verification Chat */}
      <VerificationChat
        messages={messages}
        onSendMessage={handleSendMessage}
        isLoading={isLoading}
        onSourceHover={handleSourceHover}
        onSourceLeave={handleSourceLeave}
      />
    </div>
  );
}

