"""firms

Revision ID: 2411b62ce18c
Revises: d4e5f6a7b8c9
Create Date: 2025-12-18 15:48:45.364957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2411b62ce18c'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firms_domain'), 'firms', ['domain'], unique=True)
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    op.create_index(op.f('ix_firms_name'), 'firms', ['name'], unique=True)
    op.create_index(op.f('ix_firms_qdrant_collection'), 'firms', ['qdrant_collection'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=True),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_call_id'), 'conversations', ['call_id'], unique=False)
    op.create_index(op.f('ix_conversations_firm_id'), 'conversations', ['firm_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('knowledge_base_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=100), nullable=True),
    sa.Column('qdrant_point_ids', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_files_firm_id'), 'knowledge_base_files', ['firm_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_files_id'), 'knowledge_base_files', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_files_status'), 'knowledge_base_files', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_files_user_id'), 'knowledge_base_files', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_phone_number'), 'calls', ['phone_number'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('ix_calls_twilio_call_sid'), 'calls', ['twilio_call_sid'], unique=True)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_foreign_key(None, 'firm_personas', 'firms', ['firm_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('firm_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_foreign_key(None, 'users', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.drop_column('users', 'firm_id')
    op.drop_constraint(None, 'firm_personas', type_='foreignkey')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_twilio_call_sid'), table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_phone_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_knowledge_base_files_user_id'), table_name='knowledge_base_files')
    op.drop_index(op.f('ix_knowledge_base_files_status'), table_name='knowledge_base_files')
    op.drop_index(op.f('ix_knowledge_base_files_id'), table_name='knowledge_base_files')
    op.drop_index(op.f('ix_knowledge_base_files_firm_id'), table_name='knowledge_base_files')
    op.drop_table('knowledge_base_files')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_firm_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_call_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_firms_qdrant_collection'), table_name='firms')
    op.drop_index(op.f('ix_firms_name'), table_name='firms')
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.drop_index(op.f('ix_firms_domain'), table_name='firms')
    op.drop_table('firms')
    # ### end Alembic commands ###
